[package]
name = "lek"
version = "0.1.0"
authors = ["paddi"]
edition = "2018"

[profile.release]
panic = "abort"
#lto = true
#codegen-units = 1
#incremental = false

[dependencies]
rustyline = "6.1.2"
phf = { version = "0.8", features = ["macros"] }
ansi_term = "0.12"
